# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedEvents',
            fields=[
                ('EventName', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False)),
                ('Counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserDevice', models.CharField(max_length=100)),
                ('EventName', models.CharField(max_length=100)),
                ('EventLabel', models.CharField(max_length=100)),
                ('EventAction', models.CharField(max_length=100)),
                ('EventTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UDevice',
            fields=[
                ('UID', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
