# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='udevice',
            name='UserName',
            field=models.CharField(default='UserName not mapped', max_length=100),
        ),
        migrations.AlterField(
            model_name='blockedevents',
            name='EventName',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
